---
name: linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter@v4.9.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
